Add custom-nexus-deployment.yaml

diff --git a/03_private_registry/files/nexus/custom-nexus-deployment.yaml b/03_private_registry/files/nexus/custom-nexus-deployment.yaml
--- a/03_private_registry/files/nexus/custom-nexus-deployment.yaml
+++ b/03_private_registry/files/nexus/custom-nexus-deployment.yaml
@@ -4,32 +4,6 @@ kind: Namespace
 metadata:
   name: gitops
 ---
-apiVersion: v1
-kind: PersistentVolume
-metadata:
-  name: pv-nexus
-spec:
-  capacity:
-    storage: 10Gi
-  accessModes:
-    - ReadWriteOnce
-  nfs:
-    path: /nexus-data
-    server: hostnfs
-  persistentVolumeReclaimPolicy: Retain
----
-apiVersion: v1
-kind: PersistentVolumeClaim
-metadata:
-  name: pvc-nexus
-  namespace: gitops
-spec:
-  accessModes:
-    - ReadWriteOnce
-  resources:
-    requests:
-      storage: 10Gi
----
 apiVersion: apps/v1
 kind: Deployment
 metadata:
@@ -47,38 +21,38 @@ spec:
       labels:
         app: nexus
     spec:
-      terminationGracePeriodSeconds: 60
-      volumes:
-      - name: nexus-data
-        persistentVolumeClaim:
-          claimName: pvc-nexus
+      # terminationGracePeriodSeconds: 60
+      # volumes:
+      # - name: nexus-data
+      #   persistentVolumeClaim:
+      #     claimName: pvc-nexus
       containers:
       - name: nexus
-        image: sonatype/nexus3:3.68.1-java11
+        image: sonatype/nexus3:3.68.0-java11
         ports:
         - containerPort: 8081
         - containerPort: 8082
-        readinessProbe:
-          httpGet:
-            path: /
-            port: 8081
-          initialDelaySeconds: 30
-          periodSeconds: 10
-        livenessProbe:
-          httpGet:
-            path: /
-            port: 8081
-          initialDelaySeconds: 60
-          periodSeconds: 30
-        volumeMounts:
-        - name: nexus-data
-          mountPath: /nexus-data
+        # readinessProbe:
+        #   httpGet:
+        #     path: /
+        #     port: 8081
+        #   initialDelaySeconds: 30
+        #   periodSeconds: 10
+        # livenessProbe:
+        #   httpGet:
+        #     path: /
+        #     port: 8081
+        #   initialDelaySeconds: 60
+        #   periodSeconds: 30
+        # # volumeMounts:
+        # # - name: nexus-data
+        # #   mountPath: /nexus-data
       - name: sidecar
-        image: nginx:1.27-alpine3.19-perl
-        lifecycle:
-          preStop:
-            exec:
-              command: ["/bin/sh", "-c", "nginx -s quit"]
+        image: nginx:1.26.0-alpine3.19-slim
+        # lifecycle:
+        #   preStop:
+        #     exec:
+        #       command: ["/bin/sh", "-c", "nginx -s quit"]
         command:
             - /bin/sh
             - -c
@@ -86,17 +60,22 @@ spec:
               export DOMAIN1="nexus1.pabloqpacin.com"
               export DOMAIN2="repo1.pabloqpacin.com"
 
-              timeout=60
-              while ! ping -4 -c 1 "$DOMAIN1" > /dev/null && [ $timeout -gt 0 ]; do
-                echo "Waiting for DNS resolution of $DOMAIN1..."
-                sleep 5
-                timeout=$((timeout-5))
-              done
+              # En nuestro caso el dominio resuelve a la IP de JL y mediante LB se conecta con las vms -- ICMP desactivado pero HTTP disponible!!
+              # if ! ping -4 -c 1 "$DOMAIN1" > /dev/null; then echo "Dominio no disponible"; sleep infinity; fi
+              
+              if ! curl -s "$DOMAIN1" > /dev/null; then echo "Dominio no disponible"; sleep infinity; fi
 
-              if [ $timeout -le 0 ]; then
-                echo "DNS resolution for $DOMAIN1 failed; exiting."
-                exit 1
-              fi
+              # timeout=60
+              # while ! curl -s "$DOMAIN1" > /dev/null && [ $timeout -gt 0 ]; do
+              #   echo "Waiting for DNS resolution of $DOMAIN1..."
+              #   sleep 5
+              #   timeout=$((timeout-5))
+              # done
+
+              # if [ $timeout -le 0 ]; then
+              #   echo "DNS resolution for $DOMAIN1 failed; exiting."
+              #   exit 1
+              # fi
 
               apk add certbot
 
@@ -114,23 +93,25 @@ spec:
               echo 'server { listen 443 ssl; server_name '$DOMAIN2'; client_max_body_size 1000M; location / { resolver 127.0.0.1 [::1]:8082 valid=30s; proxy_pass http://127.0.0.1:8082; proxy_redirect off; proxy_set_header Host $host; } ssl_certificate /etc/letsencrypt/live/'$DOMAIN1'/fullchain.pem; ssl_certificate_key /etc/letsencrypt/live/'$DOMAIN1'/privkey.pem; ssl_protocols TLSv1 TLSv1.1 TLSv1.2; ssl_ciphers HIGH:!aNULL:!MD5; }' >> /etc/nginx/nginx.conf
               echo '}' >> /etc/nginx/nginx.conf
 
-              exec nginx -g 'daemon off;'
+              nginx -g 'daemon off;' || true
 
+              sleep infinity
         ports:
         - containerPort: 80
         - containerPort: 443
-        readinessProbe:
-          httpGet:
-            path: /
-            port: 80
-          initialDelaySeconds: 30
-          periodSeconds: 10
-        livenessProbe:
-          httpGet:
-            path: /
-            port: 80
-          initialDelaySeconds: 60
-          periodSeconds: 30
+        # readinessProbe:
+        #   httpGet:
+        #     path: /
+        #     port: 80
+        #   initialDelaySeconds: 30
+        #   periodSeconds: 10
+        # livenessProbe:
+        #   httpGet:
+        #     path: /
+        #     port: 80
+        #   initialDelaySeconds: 60
+        #   periodSeconds: 30
+
 ---
 apiVersion: v1
 kind: Service
